# Generated by Django 5.2.14 on 2026-06-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_comments_count_blogpost_is_public_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.FileField(blank=True, default='', max_length=500, null=True, upload_to='blog_images/'),
        ),
    ]
