export const MOCK_POSTS = [
  {
    id: -1,
    title: "Designing the Next Generation of Glassmorphic Interfaces",
    subtitle: "How translucency, depth, and micro-interactions are redefining the boundaries of spatial UI design.",
    content: "Design is undergoing a quiet revolution. As screens become more high-fidelity, our visual metaphors are shifting from flat blocks to layers of physical glass. Glassmorphism combines frosted transparency, vibrant multi-layered backgrounds, and subtle hairline borders to establish clear visual hierarchy. By mimicking the optical qualities of physical materials, these interfaces reduce cognitive load while offering an exceptionally premium and futuristic aesthetic.",
    subcontent: "To build a truly great glassmorphic interface, developers must pay close attention to backdrop filters, color contrast ratios, and interactive states. A key mistake is overusing transparency, which leads to clutter. When applied selectively to prominent components—like headers, modal dialogs, and sidebars—the technique yields clean layouts that feel seamlessly integrated into their surrounding environments. Embellishing these panels with soft hover reactions completes the modern look.",
    quotation: "The future of spatial UI isn't flat. It lives in the delicate interplay between light, shadow, and glass.",
    image: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80",
    created_at: "2026-05-30T10:15:00Z",
    author: "Elena Rostova",
    author_avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=100&q=80",
    is_public: true,
    comments_count: 8,
    category: "Design",
    read_time: "5 MIN READ",
    likes: 245,
    views: 1840
  },
  {
    id: -2,
    title: "The Silent Rise of Edge Computing and Spatial Databases",
    subtitle: "Moving computation closer to the source of data to enable ultra-low latency interactive experiences.",
    content: "Every millisecond counts. In a world where instant responsiveness dictates user retention, traditional centralized cloud paradigms are reaching their physical latency limits. Edge computing solves this by distributing computation and data storage directly to regional nodes, bringing servers closer to the end-users. By routing database queries to the nearest node, we achieve latency profiles under 10 milliseconds, enabling interactive Web3, AR, and immersive canvas applications.",
    subcontent: "However, running global databases at the edge introduces complex sync problems and consistency trade-offs. Engineers must decide between eventual consistency models and high-write latencies. Modern tools like regional SQLite replication, cloudflare workers, and global distributed lock managers are making edge databases easier to deploy, promising a future where data is truly local, regardless of where in the world you click.",
    quotation: "Speed is more than a feature; it is the fundamental pre-requisite for human-centric computing.",
    image: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=800&q=80",
    created_at: "2026-05-28T14:30:00Z",
    author: "Marcus Vance",
    author_avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=100&q=80",
    is_public: true,
    comments_count: 14,
    category: "Tech",
    read_time: "7 MIN READ",
    likes: 312,
    views: 2904
  },
  {
    id: -3,
    title: "Mastering the Flow State: A Practical Guide to Deep Work",
    subtitle: "Practical strategies to eliminate context-switching, manage digital clutter, and maximize productive hours.",
    content: "We live in an age of constant interruptions. Notifications, instant messaging, and endless open tabs act as persistent micro-distractions that fragment our attention spans. Deep work—the ability to focus without distraction on a cognitively demanding task—is becoming an exceedingly rare and valuable skill. Cultivating focus isn't about working longer; it's about engineering an environment where flow state becomes the default path of least resistance.",
    subcontent: "To achieve this, implement a rigorous 'attention budget.' Designate strict blocks of time for isolated tasks, close communication tools entirely, and embrace structured boring intervals. Training your brain to tolerate silence and lack of stimulation builds the attention stamina needed to solve hard problems without immediate dopamine gratification.",
    quotation: "Who you are, what you think, feel, and do, is the sum of what you focus on.",
    image: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=800&q=80",
    created_at: "2026-05-25T09:00:00Z",
    author: "Sarah Jenkins",
    author_avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=100&q=80",
    is_public: true,
    comments_count: 5,
    category: "Productivity",
    read_time: "4 MIN READ",
    likes: 189,
    views: 1205
  },
  {
    id: -4,
    title: "The Architecture of Clean Code: Building for the Long Run",
    subtitle: "Why writing simple, highly decoupled, and self-documenting abstractions is the ultimate software developer skill.",
    content: "It is easy to write complex code. What is difficult is writing simple code that remains simple as the project grows. The best code is highly readable, easily testable, and deeply decoupled. When you construct small, focused modules with a single clear responsibility, you save yourself and your team from future technical debt. Great software design prioritizes readability over cleverness every single time.",
    subcontent: "When building applications, ask yourself: 'If another developer has to refactor this in six months, will they understand the intent within five minutes?' If the answer is no, simplify the abstraction. Avoid premature optimizations and focus on building solid foundations, clear patterns, and intuitive naming conventions that read like written English.",
    quotation: "Simplicity is the ultimate sophistication. Clean code is code that looks like it was written by someone who cares.",
    image: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=800&q=80",
    created_at: "2026-05-22T16:45:00Z",
    author: "Liam Chen",
    author_avatar: "https://images.unsplash.com/photo-1628157582853-a796fa650a6a?auto=format&fit=crop&w=100&q=80",
    is_public: true,
    comments_count: 11,
    category: "Dev",
    read_time: "6 MIN READ",
    likes: 278,
    views: 2150
  },
  {
    id: -5,
    title: "Navigating Creative Burnout: Rediscovering the Joy of Play",
    subtitle: "How stepping away from professional metrics and making things purely for fun can heal your relationship with creation.",
    content: "When your passion becomes your profession, it's easy to start viewing every creative impulse through the lens of optimization and audience reception. This metric-driven mindset is a surefire recipe for creative exhaustion and burnout. To recover your energy, you must learn to create without an expectation of outcome. Making bad art, writing unstructured prose, and coding silly scripts purely for the joy of play is vital for mental rejuvenation.",
    subcontent: "Set aside time every week to engage in hobbies that have zero professional utility. Draw, build LEGO, cook without a recipe, or take photos without posting them online. Stepping outside of productivity metrics restores the playful curiosity that made you a creator in the first place.",
    quotation: "You can't use up creativity. The more you use, the more you have, but only if you allow yourself to play.",
    image: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=800&q=80",
    created_at: "2026-05-18T11:20:00Z",
    author: "Zoe Dubois",
    author_avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=100&q=80",
    is_public: true,
    comments_count: 3,
    category: "Thoughts",
    read_time: "5 MIN READ",
    likes: 154,
    views: 980
  },
  {
    id: -6,
    title: "The Art of Slow Living in a Fast-Paced Modern World",
    subtitle: "Embracing mindfulness, conscious consumption, and intentional slowing to cultivate daily presence.",
    content: "We live in a culture that glorifies speed, hustle, and constant multitasking. But always moving fast prevents us from actually experiencing the life we are working so hard to build. Slow living isn't about doing everything at a snail's pace; it's about doing things at the right pace. It is an intentional slowing down to focus on what matters most, cultivating presence, and enjoying the richness of simple daily moments.",
    subcontent: "Start by doing one activity at a time—drink your coffee without checking your phone, take a walk without listening to a podcast, or listen fully to a friend without planning your response. Embracing these empty spaces allows your nervous system to regulate, letting you find depth and peace in a noisy world.",
    quotation: "Slow down and everything you are chasing will come around and catch you.",
    image: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=800&q=80",
    created_at: "2026-05-15T08:15:00Z",
    author: "Oliver Thorne",
    author_avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=100&q=80",
    is_public: true,
    comments_count: 6,
    category: "Lifestyle",
    read_time: "5 MIN READ",
    likes: 198,
    views: 1420
  },
  {
    id: -7,
    title: "Minimalist Workspaces: Engineering a High-Focus Studio",
    subtitle: "How spatial layout, acoustic damping, and ergonomic choice direct cognitive flow and clarity.",
    content: "Our physical environments are extensions of our cognitive processing systems. A cluttered desk is a visual noise generator, constantly calling on subconscious attention loops. Minimalist workspace design aims to remove this background interference. By standardizing clean surfaces, hidden cable channels, natural illumination, and single-task workstations, we create spatial environments that welcome deep concentration and creative release.",
    subcontent: "When arranging your workspace, place your primary monitor at eye level, incorporate soft diffusers for natural light, and introduce elements of soft biophilic design like low-maintenance indoor plants. The goal is to design a workspace that feels calm, structured, and free of physical notifications.",
    quotation: "A clean desk is a blank canvas, welcoming the full expression of your undivided attention.",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80",
    created_at: "2026-05-12T13:45:00Z",
    author: "Avery Brooks",
    author_avatar: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=100&q=80",
    is_public: true,
    comments_count: 7,
    category: "Design",
    read_time: "5 MIN READ",
    likes: 215,
    views: 1540
  },
  {
    id: -8,
    title: "The Emergence of Native Multi-Agent Systems in Software",
    subtitle: "Moving beyond simple chatbots towards autonomous networks of micro-agents collaborating on complex workflows.",
    content: "The first era of conversational AI was about prompt and response. The next era belongs to native multi-agent systems. Rather than interacting with a single general-purpose chatbot, modern engineering teams are deploying mesh networks of micro-agents, each trained for highly specialized roles. One agent drafts code, another inspects syntax against safety guidelines, a third runs functional test suites, and a coordinator merges approved changes.",
    subcontent: "This cooperative approach produces robust outputs that far surpass single-agent codebases. The challenge transitions from optimizing individual prompts to designing agent coordination structures, event brokers, and consensus mechanics, forming a collaborative virtual workspace where agents pair-program beside developers.",
    quotation: "The true potential of AI isn't individual intelligence; it is the emergent behavior of cooperative agent networks.",
    image: "https://images.unsplash.com/photo-1531747118685-ca8fa6e08806?auto=format&fit=crop&w=800&q=80",
    created_at: "2026-05-08T10:00:00Z",
    author: "Chloe Sinclair",
    author_avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=100&q=80",
    is_public: true,
    comments_count: 12,
    category: "Tech",
    read_time: "6 MIN READ",
    likes: 340,
    views: 3105
  },
  {
    id: -9,
    title: "Quiet Reading: Cultivating a Screen-Free Nightly Ritual",
    subtitle: "Why returning to physical paperbacks and dedicated analog hours protects sleep quality and mental recovery.",
    content: "Our minds are over-stimulated. By the time evening arrives, we have absorbed gigabytes of visual updates, video snippets, and notifications. Bringing active screens into the bedroom disrupts natural melatonin production and keeps our nervous systems in a vigilant state. Cultivating a screen-free nightly ritual centered around physical paperbacks offers an analog escape that gently signals to your brain that it is safe to unwind.",
    subcontent: "Try dedicating the final 60 minutes of your day to analog habits. Read a chapter of fiction, journal your reflections with a fountain pen, or listen to instrumental records in dim lighting. This tactile engagement lets your focus settle, preparing your body for restful, deep recovery.",
    quotation: "Analog spaces protect our attention in a digital world. Books are the ultimate quiet technology.",
    image: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&w=800&q=80",
    created_at: "2026-05-05T21:10:00Z",
    author: "Damian Cole",
    author_avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=100&q=80",
    is_public: true,
    comments_count: 9,
    category: "Lifestyle",
    read_time: "4 MIN READ",
    likes: 180,
    views: 1120
  }
];
